"""
tools/architect.py
───────────────────
Tool 2 — Architect
Receives DDD-based bounded context decomposition, coupling hotspots, services, 
and Mermaid.js diagrams generated by the LLM from the CodeReader output,
and writes them to disk.
"""

from __future__ import annotations

import os
from models.schemas import (
    ArchitectInput, ArchitectOutput,
    BoundedContext, CouplingHotspot, ProposedService,
    StranglerFigPlan, StranglerFigPhase
)
from utils.logger import get_logger

logger = get_logger(__name__)


def architect_tool(
    bounded_contexts: list[dict],
    proposed_services: list[dict],
    strangler_fig_plan: dict,
    mermaid_context_diagram: str,
    mermaid_class_diagram: str,
    mermaid_sequence_diagram: str,
    architecture_documentation: str,
    god_classes: list[str] = [],
    coupling_hotspots: list[dict] = []
) -> dict:
    """
    Save DDD decomposition recommendations, Mermaid.js diagrams, and architecture docs.

    Args:
        bounded_contexts: List of identified bounded contexts based on code structure.
        proposed_services: Proposed microservices decomposition.
        strangler_fig_plan: Strangler Fig routing plan.
        mermaid_context_diagram: Mermaid.js system context diagram representing the whole architecture.
        mermaid_class_diagram: Mermaid.js class diagram detailing low-level and high-level class interactions.
        mermaid_sequence_diagram: Mermaid.js sequence diagram showing interaction across bounded contexts.
        architecture_documentation: Detailed Markdown documentation describing the monolithic architecture and proposed decomposition.
        god_classes: Optional list of identified God Classes.
        coupling_hotspots: Optional list of coupling hotspots.

    Returns:
        Serialised ArchitectOutput as a plain dict (ADK requirement).
    """
    
    # Parse inputs using Pydantic models to ensure correctness
    _input = ArchitectInput(
        bounded_contexts=bounded_contexts,
        god_classes=god_classes or [],
        coupling_hotspots=coupling_hotspots or [],
        proposed_services=proposed_services,
        strangler_fig_plan=strangler_fig_plan,
        mermaid_context_diagram=mermaid_context_diagram,
        mermaid_class_diagram=mermaid_class_diagram,
        mermaid_sequence_diagram=mermaid_sequence_diagram,
        architecture_documentation=architecture_documentation
    )

    logger.info("Saving generated architecture artifacts to disk...")

    mermaid_diagrams = {
        "context": _input.mermaid_context_diagram,
        "class": _input.mermaid_class_diagram,
        "sequence": _input.mermaid_sequence_diagram
    }

    output = ArchitectOutput(
        bounded_contexts=_input.bounded_contexts,
        god_classes=_input.god_classes,
        coupling_hotspots=_input.coupling_hotspots,
        proposed_services=_input.proposed_services,
        strangler_fig_plan=_input.strangler_fig_plan,
        mermaid_diagrams=mermaid_diagrams,
        readme_decomposition=_input.architecture_documentation,
    )

    out_dir = os.path.join("output", "architecture")
    os.makedirs(out_dir, exist_ok=True)
    
    with open(os.path.join(out_dir, "README_DECOMPOSITION.md"), "w", encoding="utf-8") as f:
        f.write(output.readme_decomposition)
        
    for name, content in output.mermaid_diagrams.items():
        # Ensure mermaid contents aren't mysteriously wrapped in ```mermaid if the LLM outputted them that way
        content = content.replace("```mermaid", "").replace("```", "").strip()
        with open(os.path.join(out_dir, f"{name}.mmd"), "w", encoding="utf-8") as f:
            f.write(content)

    logger.info(
        "Decomposition complete: %d bounded contexts, %d proposed services saved.",
        len(output.bounded_contexts), len(output.proposed_services)
    )
    return output.model_dump()