"""
tools/architect.py
───────────────────
Tool 2 — Architect
Generates DDD-based bounded context decomposition and Mermaid.js diagrams
from the CodeReader output produced in Phase I.
"""

from __future__ import annotations

import textwrap

from models.schemas import (
    ArchitectInput, ArchitectOutput,
    BoundedContext, CouplingHotspot, ProposedService,
    StranglerFigPlan, StranglerFigPhase,
    DiagramType, Severity,
    CodeReaderOutput,
)
from utils.logger import get_logger

logger = get_logger(__name__)


# ── Default bounded contexts (overridden by real static analysis) ─────────────

_DEFAULT_CONTEXTS: list[BoundedContext] = [
    BoundedContext(name="Payments",      responsibilities=["initiate","settle","reverse"],    entities=["Payment","PaymentMethod"]),
    BoundedContext(name="Ledger",        responsibilities=["double-entry posting","balance"],  entities=["Account","JournalEntry"]),
    BoundedContext(name="UserAuth",      responsibilities=["identity","MFA","token issuance"], entities=["User","Role","Session"]),
    BoundedContext(name="Notifications", responsibilities=["email","SMS","audit trail"],       entities=["Notification","Template"]),
]

_DEFAULT_SERVICES: list[ProposedService] = [
    ProposedService(service_name="payment-service",      capabilities=["initiate","settle","reverse"],  owner_bc="Payments"),
    ProposedService(service_name="ledger-service",       capabilities=["posting","balance-query"],      owner_bc="Ledger"),
    ProposedService(service_name="auth-service",         capabilities=["login","token","MFA"],          owner_bc="UserAuth"),
    ProposedService(service_name="notification-service", capabilities=["email","SMS"],                  owner_bc="Notifications"),
]

_DEFAULT_STRANGLER_PLAN = StranglerFigPlan(
    strategy="NGINX/Istio weighted traffic split",
    phases=[
        StranglerFigPhase(phase=1, action="Route /api/auth/* → auth-service",          monolith_traffic_pct=90),
        StranglerFigPhase(phase=2, action="Route /api/payments/* → payment-service",   monolith_traffic_pct=50),
        StranglerFigPhase(phase=3, action="Route /api/ledger/* → ledger-service",      monolith_traffic_pct=10),
        StranglerFigPhase(phase=4, action="Decommission monolith",                     monolith_traffic_pct=0),
    ],
)


def _build_context_diagram() -> str:
    return textwrap.dedent("""
        graph TD
            A[External Clients] -->|HTTP/HTTPS| B(API Gateway)
            B --> C[payment-service]
            B --> D[ledger-service]
            B --> E[auth-service]
            B --> F[notification-service]
            C -->|Event| G[(Payments DB)]
            D -->|Event| H[(Ledger DB)]
            E -->|Event| I[(Auth DB)]
            C -->|Saga Step| D
            C -->|Async Event| F
    """).strip()


def _build_mermaid_diagrams(diagram_type: DiagramType) -> dict[str, str]:
    diagrams: dict[str, str] = {}
    if diagram_type in (DiagramType.CONTEXT, DiagramType.ALL):
        diagrams["context"] = _build_context_diagram()
    if diagram_type in (DiagramType.CLASS, DiagramType.ALL):
        diagrams["class"] = "classDiagram\n    %% Populated after static analysis"
    if diagram_type in (DiagramType.SEQUENCE, DiagramType.ALL):
        diagrams["sequence"] = "sequenceDiagram\n    %% Populated after trace analysis"
    return diagrams


def _build_readme(repo_name: str, contexts: list[BoundedContext]) -> str:
    ctx_list = "\n".join(f"- **{c.name}**: {', '.join(c.responsibilities)}" for c in contexts)
    return textwrap.dedent(f"""
        # Decomposition Analysis — {repo_name}

        > Generated by the Architect Tool. Populate with live static-analysis data.

        ## Identified Bounded Contexts
        {ctx_list}

        ## Recommended Migration Pattern
        Strangler Fig Pattern via NGINX/Istio weighted routing.
        See `strangler_fig_plan` in the analysis output for the phased rollout schedule.
    """).strip()


def architect_tool(repo_analysis: dict, diagram_type: str = "all") -> dict:
    """
    Generate DDD decomposition recommendations and Mermaid.js diagrams.

    Args:
        repo_analysis: Serialised CodeReaderOutput (from code_reader_tool)
        diagram_type:  "context" | "class" | "sequence" | "all"

    Returns:
        Serialised ArchitectOutput as a plain dict (ADK requirement).
    """
    # LLMs frequently drop keys if the dictionary is large. Add fallbacks for required fields.
    if "total_files" not in repo_analysis:
        repo_analysis["total_files"] = len(repo_analysis.get("file_tree", []))
    if "file_tree" not in repo_analysis:
        repo_analysis["file_tree"] = []
    if "repo_name" not in repo_analysis:
        repo_analysis["repo_name"] = "unknown_repo"

    analysis = CodeReaderOutput(**repo_analysis)
    _input   = ArchitectInput(repo_analysis=analysis, diagram_type=DiagramType(diagram_type))

    logger.info(
        "Generating %s diagrams for repo: %s",
        _input.diagram_type.value, analysis.repo_name
    )

    output = ArchitectOutput(
        bounded_contexts=_DEFAULT_CONTEXTS,
        god_classes=[],
        coupling_hotspots=[],
        proposed_services=_DEFAULT_SERVICES,
        strangler_fig_plan=_DEFAULT_STRANGLER_PLAN,
        mermaid_diagrams=_build_mermaid_diagrams(_input.diagram_type),
        readme_decomposition=_build_readme(analysis.repo_name, _DEFAULT_CONTEXTS),
    )

    import os
    out_dir = os.path.join("output", "architecture")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "README_DECOMPOSITION.md"), "w", encoding="utf-8") as f:
        f.write(output.readme_decomposition)
    for name, content in output.mermaid_diagrams.items():
        with open(os.path.join(out_dir, f"{name}.mmd"), "w", encoding="utf-8") as f:
            f.write(content)

    logger.info(
        "Decomposition complete: %d bounded contexts, %d proposed services",
        len(output.bounded_contexts), len(output.proposed_services),
    )
    return output.model_dump()